# -*- coding: utf-8 -*-
"""inference.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Wu5cAO5vbC0sMbc855oXJO_bH6I8Hijz
"""

import sys

sys.path.append('/content/model.py')

# Import the Seq2SeqTransformer class from the model.py file
from model import Seq2SeqTransformer,config

# Import necessary modules
from tokenizers import Tokenizer
import torch
import transformers
import argparse
import os

# Assume Seq2SeqTransformer and other necessary code is defined above

# Load the tokenizer and model
tokenizer = Tokenizer.from_file('/content/en_hi_mr_pa_te_ka_ml_or_gu_ur_ta_bn_as (1).json')

special_tokens = {
    '<unk>': 0,
    '<pad>': 1,
    '<s-en>': 2,  # bos english
    '<s-hi>': 3,  # bos hindi
    '<s-mr>': 4, # bos telugu
    '<s-pa>': 5, # bos punjabi
    '<s-te>': 6, # bos telugu
    '<s-ka>': 7, # bos kannada
    '<s-ml>': 8, # bos malayalam
    '<s-or>': 9, # bos orish
    '<s-gu>': 10, # bos gujarati
    '<s-ur>': 11, # bos urdu
    '<s-ta>': 12, # bos tamil
    '<s-bn>': 13, # bos bengali
    '<s-as>': 14, # bos asami

    # Add other languages here...
    '</s>': 15,  # eos
}

model = Seq2SeqTransformer(config)

state_dict = torch.load('/content/best_model (1).pt', map_location='cpu')
model.load_state_dict(state_dict)

# Define the translate function
def translate(input_sentence, language, d=True, t=1.0):
    # Additional checks and setup code...

    input_ids = f"<s-en>{input_sentence.strip()}</s>"
    input_ids = tokenizer.encode(input_ids).ids
    input_ids = torch.tensor(input_ids, dtype=torch.long).unsqueeze(0)
    bos = special_tokens[f"<s-{language}>"]
    outputs = model.generate(input_ids, deterministic=d, bos=bos, temperature=t)
    translation = tokenizer.decode(outputs.numpy())
    return translation

# Directly set parameters for demonstration
input_sentence =input("Enter the sentence:")
language = input("Enter language of your choice:") # Example: 'hi' for Hindi
d = True  # Deterministic
t = 1.0  # Temperature

# Call the translate function with directly set parameters
translation = translate(input_sentence=input_sentence, language=language, d=d, t=t)
print(translation)